// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default FirebaseOptions for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxrYOLGv4DBMgrFkxTVdhk_7YjvcpdZQY',
    appId: '1:928783649894:web:9b33d87571a7a3cd4b9a44',
    messagingSenderId: '928783649894',
    projectId: 'roofgriduk-f2f56',
    authDomain: 'roofgriduk-f2f56.firebaseapp.com',
    storageBucket: 'roofgriduk-f2f56.firebasestorage.app',
    measurementId: 'G-NSLE7J6VG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxrYOLGv4DBMgrFkxTVdhk_7YjvcpdZQY',
    appId: '1:928783649894:android:ff5b08a8b5753f8e4271a7',
    messagingSenderId: '928783649894',
    projectId: 'roofgriduk-f2f56',
    storageBucket: 'roofgriduk-f2f56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxrYOLGv4DBMgrFkxTVdhk_7YjvcpdZQY',
    appId: '1:928783649894:ios:ff5b08a8b5753f8e4271a7',
    messagingSenderId: '928783649894',
    projectId: 'roofgriduk-f2f56',
    storageBucket: 'roofgriduk-f2f56.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID', // Replace with actual iOS client ID
    iosBundleId: 'com.example.roofgrid_uk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxrYOLGv4DBMgrFkxTVdhk_7YjvcpdZQY',
    appId: '1:928783649894:ios:ff5b08a8b5753f8e4271a7',
    messagingSenderId: '928783649894',
    projectId: 'roofgriduk-f2f56',
    storageBucket: 'roofgriduk-f2f56.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID', // Replace with actual macOS client ID
    iosBundleId: 'com.example.roofgrid_uk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxrYOLGv4DBMgrFkxTVdhk_7YjvcpdZQY',
    appId: '1:928783649894:web:8a971a8e754326b94b9a44',
    messagingSenderId: '928783649894',
    projectId: 'roofgriduk-f2f56',
    authDomain: 'roofgriduk-f2f56.firebaseapp.com',
    storageBucket: 'roofgriduk-f2f56.firebasestorage.app',
    measurementId: 'G-S7DYPHPP56',
  );
}
