// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default FirebaseOptions for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNG0Vkaid36qLuMzbNtLPT4j3iwGvLMUo',
    appId: '1:796676497165:web:9b33d87571a7a3cd4b9a44',
    messagingSenderId: '796676497165',
    projectId: 'roofgriduk',
    authDomain: 'roofgriduk.firebaseapp.com',
    storageBucket: 'roofgriduk.firebasestorage.app',
    measurementId: 'G-NSLE7J6VG0',
  );

  // Replace placeholder values with actual Firebase configuration values

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgi4VoHLXRddBv2hLybGGrTi93yBCTi4U',
    appId: '1:796676497165:android:ffcb241b044d6a694b9a44',
    messagingSenderId: '796676497165',
    projectId: 'roofgriduk',
    storageBucket: 'roofgriduk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBNG0Vkaid36qLuMzbNtLPT4j3iwGvLMUo",
    appId: "1:796676497165:web:9b33d87571a7a3cd4b9a44",
    messagingSenderId: "796676497165",
    projectId: "roofgriduk",
    storageBucket: "roofgriduk.firebasestorage.app",
    iosClientId:
        "YOUR_IOS_CLIENT_ID", // You'll need to replace this if you use iOS
    iosBundleId: "com.roofgriduk.app",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyBNG0Vkaid36qLuMzbNtLPT4j3iwGvLMUo",
    appId: "1:796676497165:web:9b33d87571a7a3cd4b9a44",
    messagingSenderId: "796676497165",
    projectId: "roofgriduk",
    storageBucket: "roofgriduk.firebasestorage.app",
    iosClientId:
        "YOUR_IOS_CLIENT_ID", // You'll need to replace this if you use macOS
    iosBundleId: "com.roofgriduk.app",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNG0Vkaid36qLuMzbNtLPT4j3iwGvLMUo',
    appId: '1:796676497165:web:8a971a8e754326b94b9a44',
    messagingSenderId: '796676497165',
    projectId: 'roofgriduk',
    authDomain: 'roofgriduk.firebaseapp.com',
    storageBucket: 'roofgriduk.firebasestorage.app',
    measurementId: 'G-S7DYPHPP56',
  );

}