import 'package:roofgrid_uk/models/tile_model.dart';

/// Standard UK tile profiles for local-only developer seeding.
List<TileModel> buildUkSeedTiles(String userId) {
  final now = DateTime.now();
  return [
    TileModel(
      id: 'dev-slate-1',
      name: 'Natural Slate',
      manufacturer: 'Generic',
      materialType: TileSlateType.slate,
      description: '500×250mm natural slate (BS 5534 gauge range)',
      isPublic: true,
      isApproved: true,
      createdById: userId,
      createdAt: now,
      updatedAt: now,
      slateTileHeight: 500,
      tileCoverWidth: 250,
      minGauge: 195,
      maxGauge: 210,
      minSpacing: 1,
      maxSpacing: 5,
      defaultCrossBonded: true,
      image: 'assets/images/tiles/natural_slate.jpg',
    ),
    TileModel(
      id: 'dev-plain-1',
      name: 'Clay Plain Tile',
      manufacturer: 'Generic',
      materialType: TileSlateType.plainTile,
      description: '265×165mm clay plain tile',
      isPublic: true,
      isApproved: true,
      createdById: userId,
      createdAt: now,
      updatedAt: now,
      slateTileHeight: 265,
      tileCoverWidth: 165,
      minGauge: 85,
      maxGauge: 115,
      minSpacing: 1,
      maxSpacing: 7,
      defaultCrossBonded: true,
      image: 'assets/images/tiles/plain_tile.png',
    ),
    TileModel(
      id: 'dev-concrete-1',
      name: 'Concrete Interlocking',
      manufacturer: 'Generic',
      materialType: TileSlateType.interlockingTile,
      description: '420×330mm concrete interlocking tile',
      isPublic: true,
      isApproved: true,
      createdById: userId,
      createdAt: now,
      updatedAt: now,
      slateTileHeight: 420,
      tileCoverWidth: 300,
      minGauge: 310,
      maxGauge: 345,
      minSpacing: 1,
      maxSpacing: 5,
      defaultCrossBonded: false,
      image: 'assets/images/tiles/interlocking_tile.jpg',
    ),
    TileModel(
      id: 'dev-concrete-flat-1',
      name: 'Concrete Plain Tile',
      manufacturer: 'Generic',
      materialType: TileSlateType.concreteTile,
      description: '420×330mm concrete plain tile',
      isPublic: true,
      isApproved: true,
      createdById: userId,
      createdAt: now,
      updatedAt: now,
      slateTileHeight: 420,
      tileCoverWidth: 300,
      minGauge: 310,
      maxGauge: 345,
      minSpacing: 1,
      maxSpacing: 5,
      defaultCrossBonded: false,
      image: 'assets/images/tiles/concrete_tile.jpg',
    ),
    TileModel(
      id: 'dev-fibre-1',
      name: 'Fibre Cement Slate',
      manufacturer: 'Generic',
      materialType: TileSlateType.fibreCementSlate,
      description: '600×300mm fibre cement slate',
      isPublic: true,
      isApproved: true,
      createdById: userId,
      createdAt: now,
      updatedAt: now,
      slateTileHeight: 600,
      tileCoverWidth: 300,
      minGauge: 235,
      maxGauge: 255,
      minSpacing: 1,
      maxSpacing: 5,
      defaultCrossBonded: true,
      image: 'assets/images/tiles/fibre_cement_slate.jpg',
    ),
  ];
}